### ISSUE TITLE
Refer to subprocess after R session restart

### ISSUE THREAD

**Issue by Tazovsky** [lbartnik/subprocess#43]
I'm looking for solution to create async process in shiny application and after application restart/close be able to check if process is still running/finished, etc. - that's why I did simple experiment:

```r 
# save 
save(handle, file = "/src/dev/subprocess/handle.RData")
# load after session restart
load("/src/dev/subprocess/handle.RData")
subprocess::process_state(handle)
Error in subprocess::process_state(handle) : external C pointer is NULL```

So my question is: is there any possibility to do this using `subprocess` package?

**Comment by lbartnik** [comment]
Hi, I'm afraid this is not straightforward. It seems that restart/close means actually restarting R. Am I right? In that case, the child process is lost and there's no way to obtain its handle after the restart. You would need to find a way to keep the R process running regardless of what happens when the shiny app.

**Comment by bedantaguru** [comment]
It is not possible by the very definition of the package. as @lbartnik said if you want to keep it alive you need to keep the session active.

**Comment by lbartnik** [comment]
Closing at the original issuer did not respond.
